name: Publish Docker
on:
  push: {}
  schedule:
    - cron: "0 3 * * 2"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: sylwekrapala/jupyter-rust
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        dockerfile: Dockerfile
